### PR TITLE
update getting started

### PR DESCRIPTION
**Pull request by CaroMac**
update Getting Started button on Landing page to point to Intro and Architecture
add info about which MacOS download to choose for the cli tool
add info about potential error messages when renaming
add info about PATH

### CODE REVIEW

**Comment by CaroMac** [comment]
This is to address [Doc: Not obvious which MacOSX download required#1539](https://github.com/galasa-dev/projectmanagement/issues/1539) and [Doc: getting started for new user on Mac is not straightforward/ obvious#1541](https://github.com/galasa-dev/projectmanagement/issues/1541)

**Review by matcomer — CHANGES_REQUESTED** [review]
Firstly thank you for making these changes.

I am happy with the first one (for providing guidance on which download is applicable depending on the type of Mac)
My one comment on this (as briefly discussed with you Caroline), for many Mac users, it may be obvious which download is required (even though it wasn't obvious to me). Perhaps the statement can be indented or given a sub heading and put on a separate line so it has less emphasis?

For the second change (concerning the path and access), thank you for the update. Its great to have the some more content on this. I think this one is more complex and so needs a little more thought.

a) similar to comment above, I would suggest separating this extra help from the required step (so as not to confuse those who are more familiar with Macs/ command lines and this is a no brainer for them). i.e. keep "After downloading the binary, re-name it to `galasactl`." as-is - then have the new wording as a separate sub-section that optionally provides more guidance for those who need more help.
b) I would change the ordering. I did the PATH and chmod steps first. It wasn't till after these that I hit the '...cannot be opened because it is from an unidentified developer' issue
c) the following new text "_... click `OK`, go to `Privacy & Security` in your System Settings, and click `Open Anyway`. Alternatively, control-click the downloaded icon, choose `Open` from the pop-up menu and then click `Open`._" is not quite right
i) I had to go to `Privacy & Security` in your System Settings
ii) I had to select 'Developer tools'
iii) I had to add 'galasactl' using the plus icon
iv) important piece here: running from a CLI still would not work at this point. I had to run Galasa from Finder. To do this 'Right click galasctl in Developer tools' and 'select Show in Finder'. Then 'double click on galasactl in Finder'. This then presents a surety warning that has to be accepted (I can no longer reproduce now mine is setup, so can't recall the exact wording'. Only then galasactl would work
v) Once galasactl had worked successfully through Finder, I was then able to run through a terminal/ CLI

My recommendation would be to find someone with a Mac who hasn't used Galasa before and try walk through these steps for yourself. I appreciate this is a pain, may take some time but would help you see for yourself

**Comment by techcobweb** [comment]
See https://github.com/galasa-dev/projectmanagement/issues/1551 for an extra step on the command-line which allows the galasactl executable to be executed.

**Review by techcobweb — CHANGES_REQUESTED** [review]
Add the https://github.com/galasa-dev/projectmanagement/issues/1551 detail, and the `uname -m` detail ?

**Comment by CaroMac** [comment]
Hi @matcomer , thank you for the review and the comments. I have an M1 Mac and I did try out the steps I documented on my machine and it worked for me. I always do this where possible to make sure the instructions are correct.  I also tried out the Windows instructions on a Windows machine. I think you might not have an M1 (based on the download you needed), so I guess that there are some differences in the menu options etc. I  think the cleanest way forward is therefore to just use ```uname -m``` (as @techcobweb mentioned) to get the machine architecture, and that removes the complexity of differences between models menu options.  The development of https://github.com/galasa-dev/projectmanagement/issues/1551 should also make things easier as it will allow the galasactl executable to be executed without having to do the various other steps that seem to be slightly different depending on what Mac you have. I like the idea of the indenting / separating the extra help so will incorporate that formatting in the update.

**Comment by CaroMac** [comment]
> If you are on a mac, you can use `uname -m` to get the machine architecture. Values will be `arm64` or `amd64`, and you can use that to guide you on which file to download.

@techcobweb I chatted with Mat before I went on holiday and his system returned 'x86_64' when he typed `name -m`. Mine returns arm64.

**Review by techcobweb — APPROVED** [review]

**Review by matcomer — APPROVED** [review]

**Comment by matcomer** [comment]
This looks much clearer - thank you. 
Approving

**Pull request merged**
