### PR TITLE
example project update

### PR DESCRIPTION
**Pull request by CaroMac**

### CODE REVIEW

**Comment by CaroMac** [comment]
https://github.com/galasa-dev/projectmanagement/issues/810

**Comment by CaroMac** [comment]
New instructions verified on walkthrough with Tom S

**Review by DavidXRoberts — APPROVED** [review]
I've now successfully run through the instructions

**Comment by CaroMac** [comment]
Thank you.

**Review by Jimbo4794 — APPROVED** [review]

**Pull request merged**
