### PR TITLE
clarification about hidden files

### PR DESCRIPTION
**Pull request by hobbit1983**
Signed-off-by: Will Yates <hobbit1983@gmail.com>

### CODE REVIEW

**Comment by hobbit1983** [comment]
So in honesty you can just type `cd` without the `~` to go to a users home directory. perhaps we can say that the command cd ~/.galasa will change into the users home directory on MACOS and linux - however we would need to know the same for windows.  So I left it out.  However if you want we could find out how to do the same in windows and include it?

**Comment by CaroMac** [comment]
So just tried it out in windows and it looks like you just get the run dialogue box up and enter 'cmd' and that takes you there.

**Comment by CaroMac** [comment]
Maybe something along the lines of : 
Locate your user home directory and confirm it contains a `.galasa` folder. On Windows, the user home directory resembles: `C:\Users\<username>`, on MacOS it will be `/Users/<username>` and on Linux `/home/<username>`. On MacOS or Linux, entering cd in a terminal takes you to your user home directory, whatever it has been configured to be. On Windows, entering `cmd` in the Run dialogue box gets you there. Note that any file or folder beginning with a `.` is a hidden folder so you might need to change the setting on your operating system to show hidden files.

**Comment by hobbit1983** [comment]
The danger is that typing cmd in the run dialog in windows just opens the command prompt. Which might not be at the users home directory

**Pull request merged**
