### PR TITLE
Styles v2

### PR DESCRIPTION
**Pull request by ind1go**

### CODE REVIEW

**Comment by Michael-Baylis** [comment]
@ind1go In the Docs section,  the yellow bar under the title doesn't look all that nice.

**Comment by JonCollettIBM** [comment]
@ind1go Just some observations.....
1. Firstly, I wanted to say that I like what you have done. Particularly:

-  the code snippets now being colour coded (much clearer/easier to read).

- the introduction of a bit of colour into the website (landing page etc.) makes it look more permanent/professional (IMHO)

2. I am not certain what the graphic on the landing page is suposed to represent? Having said that, I quite like it (it reminded me of potting snooker balls :-) ). I think this is an improvement on the previous landing page.
3. Ooo hang on....... I completely missed that the landing page is scrollable and went straight into clicking on the first two buttons. Could we possibly move the "Lighten the load with automation (and its associated graphic) up a bit please?  (and then it will make it obvious that there is more to read below). And having discovered the bottom half of the landing page, the Mondrian style graphics complement the first graphic (and vice versa).
4. I read Mike's comments on the yellow bars, but I quite like them. Once I had discovered the bottom half of the landing page, the 'highlighting' ties everything together (just my opinion).
5. The Galasa heading has a scroll bar all of its own. Are we intending to use this later for something, if not, can we remove it please, as it looks a bit odd?
6.  On the Managers page, the labels alpha/beta/ga are no longer uniform. Can we make the label appear under the Manager name please ? (as opposed to some appearing next to the manager name - just to unify things - my guess is that this is a name length issue).
7. I missed the subtlety of the different colours used on the Manager names, indicating a link. Can we have the best of both worlds please i.e. your nice colouring AND the underlining? (if a user has a problem with colours/are colourblind, the underlining will still make it obvious that there is a link).

Overall, I think it looks great.

**Comment by ind1go** [comment]
@JonCollettIBM could you screenshot your point 5? I think this must be a Windowsism.
> The Galasa heading has a scroll bar all of its own. Are we intending to use this later for something, if not, can we remove it please, as it looks a bit odd?

**Comment by JonCollettIBM** [comment]
@ind1go Hi Ben, here is the screenshot as requested:

image
[I should say that I used that latest version of Firefox (72.0.2 (64 bit)]

It looks even worse in Chrome (because it is white):
image
[This was in Chrome version 79.03945.130]

And just to complete the set....
In Microsoft Edge browser it is grey:
image
[I have no idea what version of Edge this is (but asssume it is the latest)  - it seems that Microsoft wants to conceal the version.]. 

I hope that helps.

**Comment by cxharris** [comment]
For Ben: Just a reminder that some of the new .svg diagrams contain text that defaults to a Serif font, making them harder to read.

**Comment by ind1go** [comment]
> For Ben: Just a reminder that some of the new .svg diagrams contain text that defaults to a Serif font, making them harder to read.

Thanks @cxharris - should be resolved now.

**Comment by ind1go** [comment]
> The Galasa heading has a scroll bar all of its own. Are we intending to use this later for something, if not, can we remove it please, as it looks a bit odd?

@JonCollettIBM it's now resolved (and a few other errant scrollbars around the place) - should feel much cleaner now.

**Comment by JonCollettIBM** [comment]
@ind1go That looks much cleaner, thanks Ben.

**Pull request merged**
