### PR TITLE
add link to javadoc in managers topic

### PR DESCRIPTION
**Pull request by CaroMac**

### CODE REVIEW

**Comment by CaroMac** [comment]
Hi, yes I think https://javadoc.galasa.dev/ is better, thanks. When I click on the link in the Docker Container twistie in https://galasa.dev/docs/managers/docker-manager  and then clicked overview, it took me here https://javadoc-snapshot.galasa.dev/overview-summary.html which is why I had put that link in initially. I did think about adding a link to the relevant manager within each Manager overview section in the website as well if you think that would be useful.  So eg in Artifact Manager I can add https://javadoc.galasa.dev/dev/galasa/artifact/package-summary.html link in the overview section.

**Comment by hobbit1983** [comment]
Those links you found should not point to the snapshot. Is that content generated from the code?  Can you update them as part of this PR

**Comment by CaroMac** [comment]
Yes it is part of the code. Will look to see where it gets generated from.

**Comment by hobbit1983** [comment]
Yes if we could add links in to the java doc from each managers documentation that would be great. If you spot deficiencies in the java doc as you do the updating please let me know and we can raise issues to get it fixed

**Comment by CaroMac** [comment]
Will do, thx.

**Comment by CaroMac** [comment]
Updated link in mangers.md. Will need to add links for  the individual managers via the relevant files in the managers repo.

**Pull request merged**
